#!/bin/bash
# Report generation — Markdown with professional formatting

generate_md_report() {
  local output_file="$1"
  local avg=0
  local grade="F"

  if [[ $TOTAL_MODULES -gt 0 ]]; then
    avg=$((TOTAL_SCORE / TOTAL_MODULES))
  fi

  if [[ $avg -ge 90 ]]; then grade="A+"
  elif [[ $avg -ge 80 ]]; then grade="A"
  elif [[ $avg -ge 70 ]]; then grade="B"
  elif [[ $avg -ge 60 ]]; then grade="C"
  elif [[ $avg -ge 50 ]]; then grade="D"
  fi

  # Build score table
  local score_table=""
  for module in $(for k in "${!SCORES[@]}"; do echo "$k"; done | sort); do
    local s=${SCORES[$module]}
    local emoji="🟢"
    [[ $s -lt 60 ]] && emoji="🔴"
    [[ $s -ge 60 && $s -lt 80 ]] && emoji="🟡"
    [[ $s -ge 80 ]] && emoji="🟢"
    score_table+="| $emoji $module | **$s**/100 |"$'\n'
  done

  # Quick wins
  local quick_wins=""
  local sorted_scores=$(for k in "${!SCORES[@]}"; do echo "${SCORES[$k]} $k"; done | sort -n)
  local win_count=0
  while IFS= read -r line; do
    local s=$(echo "$line" | awk '{print $1}')
    local m=$(echo "$line" | awk '{$1=""; print $0}' | xargs)
    if [[ $s -lt 80 && $win_count -lt 5 ]]; then
      quick_wins+="- **$m** ($s/100) — focus here for biggest impact"$'\n'
      ((win_count++))
    fi
  done <<< "$sorted_scores"

  # Write the report
  cat > "$output_file" << MDHEADER
# 🔍 TryAppStack Audit Report

> **Project:** $PROJECT_NAME
> **Framework:** $FRAMEWORK_DISPLAY
> **Language:** $LANG_DISPLAY
> **Package Manager:** $PKG_MANAGER
> **Date:** $DATE_DISPLAY
> **Overall Score:** **$avg/100 (Grade: $grade)**
$(if $AI_ENABLED; then echo "> **AI:** $AI_PROVIDER ✨"; fi)

---

## 📋 Scorecard

| Module | Score |
|--------|-------|
$score_table
| **Overall** | **$avg/100 ($grade)** |

---

## 💡 Priority Actions

$quick_wins

---

$REPORT_BODY

---

## 📊 Thresholds Reference ($FRAMEWORK_DISPLAY)

$(print_thresholds_md)

---

*Generated by [tryappstack-audit](https://github.com/tryappstack/audit) v${VERSION}*
MDHEADER

}

print_thresholds_md() {
  case "$FRAMEWORK" in
    react*|nextjs*)
      cat << 'EOF'
| File Type | ✅ Clean | 🟡 Warning | 🔴 Critical |
|-----------|----------|------------|-------------|
| Pages | < 200 | > 300 | > 500 |
| Components | < 100 | > 200 | > 400 |
| Hooks | < 80 | > 150 | — |
| Utils/Lib | < 80 | > 150 | > 300 |
| UI Primitives | < 50 | > 100 | > 200 |
EOF
      ;;
    angular)
      cat << 'EOF'
| File Type | ✅ Clean | 🟡 Warning | 🔴 Critical |
|-----------|----------|------------|-------------|
| Components | < 150 | > 250 | > 500 |
| Services | < 100 | > 150 | > 300 |
| Guards/Pipes | < 80 | > 200 | — |
| Modules | < 60 | > 200 | — |
EOF
      ;;
    vue*|nuxt)
      cat << 'EOF'
| File Type | ✅ Clean | 🟡 Warning | 🔴 Critical |
|-----------|----------|------------|-------------|
| Views/Pages | < 200 | > 250 | > 400 |
| Components | < 100 | > 200 | > 350 |
| Composables | < 80 | > 100 | — |
| Stores | < 80 | > 150 | > 300 |
EOF
      ;;
    *)
      cat << 'EOF'
| File Type | ✅ Clean | 🟡 Warning | 🔴 Critical |
|-----------|----------|------------|-------------|
| Controllers/Routes | < 100 | > 150 | > 300 |
| Services | < 100 | > 150 | > 300 |
| Middleware | < 60 | > 200 | — |
| Utils | < 80 | > 150 | > 300 |
EOF
      ;;
  esac
}

# Console scorecard (colored)
print_scorecard_console() {
  if [[ $TOTAL_MODULES -eq 0 ]]; then return; fi

  local avg=$((TOTAL_SCORE / TOTAL_MODULES))
  local grade="F" gc="$RED"
  [[ $avg -ge 90 ]] && grade="A+" && gc="$GREEN"
  [[ $avg -ge 80 && $avg -lt 90 ]] && grade="A" && gc="$GREEN"
  [[ $avg -ge 70 && $avg -lt 80 ]] && grade="B" && gc="$CYAN"
  [[ $avg -ge 60 && $avg -lt 70 ]] && grade="C" && gc="$YELLOW"
  [[ $avg -ge 50 && $avg -lt 60 ]] && grade="D" && gc="$YELLOW"

  echo -e "  ${BOLD}┌────────────────────────────────────────────────────────────────┐${NC}"
  echo -e "  ${BOLD}│                      📋 SCORECARD                              │${NC}"
  echo -e "  ${BOLD}├────────────────────────────────────────────────────────────────┤${NC}"

  for module in $(for k in "${!SCORES[@]}"; do echo "${SCORES[$k]} $k"; done | sort -rn | awk '{$1=""; print $0}' | xargs -I{} echo {}); do
    local s=${SCORES[$module]}
    local bar_w=30
    local filled=$((s * bar_w / 100))
    local bar="" empty=""
    for ((i=0; i<filled; i++)); do bar+="█"; done
    for ((i=filled; i<bar_w; i++)); do empty+="░"; done

    local sc="$RED"
    [[ $s -ge 80 ]] && sc="$GREEN"
    [[ $s -ge 60 && $s -lt 80 ]] && sc="$YELLOW"

    printf "  ${BOLD}│${NC} %-18s ${sc}%s${NC}${DIM}%s${NC} %3d ${BOLD}│${NC}\n" "$module" "$bar" "$empty" "$s"
  done

  echo -e "  ${BOLD}├────────────────────────────────────────────────────────────────┤${NC}"
  printf "  ${BOLD}│${NC}  Overall: ${gc}${BOLD}%d/100 (Grade: %s)${NC}%*s${BOLD}│${NC}\n" "$avg" "$grade" $((35 - ${#grade})) ""
  echo -e "  ${BOLD}└────────────────────────────────────────────────────────────────┘${NC}"
}

# Quick wins console
print_quick_wins() {
  local sorted=$(for k in "${!SCORES[@]}"; do echo "${SCORES[$k]} $k"; done | sort -n | head -3)
  local has_wins=false

  while IFS= read -r line; do
    local s=$(echo "$line" | awk '{print $1}')
    local m=$(echo "$line" | awk '{$1=""; print $0}' | xargs)
    if [[ $s -lt 80 ]]; then
      if ! $has_wins; then
        echo -e "  ${BOLD}💡 Quick Wins${NC}"
        has_wins=true
      fi
      echo -e "  ${YELLOW}→${NC} ${BOLD}$m${NC} ($s/100)"
    fi
  done <<< "$sorted"
}

export -f generate_md_report print_thresholds_md print_scorecard_console print_quick_wins
