const fs = require("fs");
const path = require("path");
const chalk = require("chalk");
const ora = require("ora");
const { callAI, getProviderName } = require("../ai/runner");
const { getLatestReport, extractProjectInfo, extractScoresFromReport } = require("../utils/helpers");

const BRAND = chalk.hex("#c8ff00");

async function aiEstimateCommand(directory, opts) {
    const dir = path.resolve(directory);

    const report = getLatestReport(dir);
    if (!report) {
        console.log(chalk.red("\n  ✗ No audit reports found in ./audits/"));
        console.log(chalk.dim("  Run an audit first: ") + BRAND("npx tryappstack-audit"));
        process.exit(1);
    }

    const { project, framework, score } = extractProjectInfo(report.content);
    const scores = extractScoresFromReport(report.content);

    const scoreLines = Object.entries(scores)
        .sort((a, b) => a[1] - b[1])
        .map(([mod, s]) => `- ${mod}: ${s}/100`)
        .join("\n");

    const provider = getProviderName(opts);
    console.log(`\n  ${chalk.bold("⏱  AI Tech Debt Estimate")} ${chalk.dim(`· ${provider}`)}`);
    console.log(chalk.dim(`  Project: ${project} · Framework: ${framework} · Score: ${score ?? "??"}/100`));
    console.log(chalk.dim(`  Based on: ${report.filename}\n`));

    const spinner = ora({ text: "  Calculating tech debt estimate...", color: "yellow" }).start();

    const prompt = `You are a senior engineer estimating tech debt for a ${framework} project called "${project}".

Current audit scores (lower = more debt):
${scoreLines}

Provide a detailed time estimation. Format exactly as:

## ⏱ Tech Debt Breakdown

| Module | Score | Effort | Hours | Complexity | Priority |
|--------|-------|--------|-------|------------|----------|
| [module] | X/100 | [Low/Med/High] | ~Xh | [Simple/Moderate/Complex] | [P1/P2/P3] |

## 🎯 Score Milestones

| Target Score | Hours Required | Developer Profile |
|-------------|----------------|------------------|
| 70/100 | ~Xh | [e.g. 1 mid-level dev] |
| 80/100 | ~Xh | [e.g. 1 senior dev] |
| 90/100 | ~Xh | [e.g. 1 senior + 1 specialist] |

## 💰 Cost Estimate (assuming $80/hr blended rate)
- **To reach 70:** ~$X
- **To reach 80:** ~$X
- **To reach 90:** ~$X

## 🔥 Biggest ROI Fixes
Top 3 changes that give the most score improvement for the least effort:
1. **Fix name** — +X score pts, ~Xh
2. **Fix name** — +X score pts, ~Xh
3. **Fix name** — +X score pts, ~Xh

## 📅 Recommended Timeline
- **1 developer, full time:** complete in X weeks
- **2 developers:** complete in X weeks

Be realistic and specific to ${framework}. No generic advice.`;

    let result;
    try {
        result = await callAI([{ role: "user", content: prompt }], opts);
        spinner.stop();
    } catch (err) {
        spinner.stop();
        if (err.noKey) {
            console.log(chalk.yellow("  ⚠ AI not configured."));
            console.log(chalk.dim("  Run: ") + BRAND("npx tryappstack-audit ai-setup"));
        } else {
            console.log(chalk.red(`  ✗ AI error: ${err.message}`));
        }
        process.exit(1);
    }

    console.log(result.split("\n").map((l) => "  " + l).join("\n"));

    // Save to file
    const timestamp = new Date().toISOString().slice(0, 10);
    const outputDir = path.join(dir, "audits");
    fs.mkdirSync(outputDir, { recursive: true });
    const outputFile = path.join(outputDir, `tech-debt-estimate-${timestamp}.md`);

    const fileContent = `# ⏱ Tech Debt Estimate — ${project}

> **Project:** ${project}
> **Framework:** ${framework}
> **Current Score:** ${score ?? "??"}/100
> **Generated:** ${new Date().toISOString().slice(0, 19)}
> **AI Agent:** ${provider}
> **Based on:** ${report.filename}

---

${result}

---

*Generated by [tryappstack-audit](https://tryappstack.vercel.app) · Tech debt estimate*
`;

    fs.writeFileSync(outputFile, fileContent);
    console.log("\n  " + chalk.green("✓") + " Saved: " + chalk.dim(outputFile) + "\n");
}

module.exports = aiEstimateCommand;
