const fs = require("fs");
const path = require("path");
const chalk = require("chalk");
const ora = require("ora");
const { callAI, getProviderName } = require("../ai/runner");
const { getLatestReport, extractProjectInfo, extractScoresFromReport } = require("../utils/helpers");

const BRAND = chalk.hex("#c8ff00");

async function aiPlanCommand(directory, opts) {
    const dir = path.resolve(directory);

    // Load latest report
    const report = getLatestReport(dir);
    if (!report) {
        console.log(chalk.red("\n  ✗ No audit reports found in ./audits/"));
        console.log(chalk.dim("  Run an audit first: ") + BRAND("npx tryappstack-audit"));
        process.exit(1);
    }

    const { project, framework, score } = extractProjectInfo(report.content);
    const scores = extractScoresFromReport(report.content);

    // Build scores summary
    const scoreLines = Object.entries(scores)
        .sort((a, b) => a[1] - b[1])
        .map(([mod, s]) => `- ${mod}: ${s}/100`)
        .join("\n");

    // Extract issues section from report
    const issuesSection = report.content.match(/## 🔍 Issues([\s\S]+?)(?=\n---|\n## |$)/)?.[1] || "";

    const provider = getProviderName(opts);
    console.log(`\n  ${chalk.bold("📋 AI Sprint Plan")} ${chalk.dim(`· ${provider}`)}`);
    console.log(chalk.dim(`  Project: ${project} · Framework: ${framework} · Score: ${score ?? "??"}/100`));
    console.log(chalk.dim(`  Based on: ${report.filename}\n`));

    const spinner = ora({ text: "  Generating sprint plan...", color: "yellow" }).start();

    const prompt = `You are a principal engineer generating a sprint refactoring plan for a ${framework} project called "${project}".

Current audit scores:
${scoreLines}

${issuesSection ? `Issues found:\n${issuesSection.slice(0, 1500)}` : ""}

Generate a structured **2-Week Sprint Refactoring Plan** to improve the code quality. Format exactly as:

## 🏃 Sprint 1 — Critical Fixes (Days 1–5)
For each task:
- [ ] **Task name** — description, expected +N score improvement, ~Xh
*(focus on security, dead code, unused packages — highest impact)*

## 🔧 Sprint 2 — Quality & Performance (Days 6–10)
For each task:
- [ ] **Task name** — description, expected +N score improvement, ~Xh
*(focus on complexity, best practices, performance)*

## 🎯 Post-Sprint Goals
- [ ] Long-term architectural improvements

## 📊 Expected Score After Plan
| Timeline | Projected Score |
|----------|----------------|
| After Sprint 1 | X/100 |
| After Sprint 2 | X/100 |
| After Post-Sprint | X/100 |

Be specific to ${framework} patterns. No generic advice. Keep tasks actionable.`;

    let result;
    try {
        result = await callAI([{ role: "user", content: prompt }], opts);
        spinner.stop();
    } catch (err) {
        spinner.stop();
        if (err.noKey) {
            console.log(chalk.yellow("  ⚠ AI not configured."));
            console.log(chalk.dim("  Run: ") + BRAND("npx tryappstack-audit ai-setup"));
        } else {
            console.log(chalk.red(`  ✗ AI error: ${err.message}`));
        }
        process.exit(1);
    }

    // Display
    console.log(result.split("\n").map((l) => "  " + l).join("\n"));

    // Save to file
    const timestamp = new Date().toISOString().slice(0, 10);
    const outputDir = path.join(dir, "audits");
    fs.mkdirSync(outputDir, { recursive: true });
    const outputFile = path.join(outputDir, `sprint-plan-${timestamp}.md`);

    const fileContent = `# 📋 AI Sprint Plan — ${project}

> **Project:** ${project}
> **Framework:** ${framework}
> **Current Score:** ${score ?? "??"}/100
> **Generated:** ${new Date().toISOString().slice(0, 19)}
> **AI Agent:** ${provider}
> **Based on:** ${report.filename}

---

${result}

---

*Generated by [tryappstack-audit](https://tryappstack.vercel.app) · Sprint plan*
`;

    fs.writeFileSync(outputFile, fileContent);
    console.log("\n  " + chalk.green("✓") + " Saved: " + chalk.dim(outputFile) + "\n");
}

module.exports = aiPlanCommand;
