const fs = require("fs");
const path = require("path");
const readline = require("readline");
const chalk = require("chalk");
const ora = require("ora");
const { callAI, getProviderName } = require("../ai/runner");
const { getLatestReport, extractProjectInfo, sanitizeForAI } = require("../utils/helpers");

const BRAND = chalk.hex("#c8ff00");

const MAX_FILE_BYTES = 40000; // ~40KB limit to keep tokens reasonable

async function aiReviewCommand(filePath, opts) {
    const absPath = path.resolve(filePath);

    if (!fs.existsSync(absPath)) {
        console.log(chalk.red(`\n  ✗ File not found: ${absPath}\n`));
        process.exit(1);
    }

    const ext = path.extname(absPath).toLowerCase();
    const allowed = [".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs", ".vue", ".svelte"];
    if (!allowed.includes(ext)) {
        console.log(chalk.yellow(`\n  ⚠ Unsupported file type: ${ext}`));
        console.log(chalk.dim(`  Supported: ${allowed.join(", ")}\n`));
        process.exit(1);
    }

    const stat = fs.statSync(absPath);
    if (stat.size > MAX_FILE_BYTES) {
        console.log(chalk.yellow(`\n  ⚠ File too large (${Math.round(stat.size / 1024)}KB). Max 40KB.`));
        console.log(chalk.dim("  Consider reviewing a smaller, focused file.\n"));
        process.exit(1);
    }

    const provider = getProviderName(opts);
    const filename = path.basename(absPath);

    console.log(`\n  ${chalk.bold("🔎 AI File Review")} ${chalk.dim(`· ${provider}`)}`);
    console.log(chalk.dim(`  File: ${absPath}`));
    console.log(chalk.dim(`  Size: ${Math.round(stat.size / 1024 * 10) / 10}KB\n`));

    // Consent prompt — file contents will be sent
    console.log(chalk.yellow("  ⚠  File contents will be sent to your AI provider."));
    console.log(chalk.dim("  Secrets/tokens are auto-redacted before sending.\n"));

    const confirmed = await confirmPrompt("  Continue? (y/N): ");
    if (!confirmed) {
        console.log(chalk.dim("\n  Cancelled.\n"));
        return;
    }

    // Read & sanitize
    let content = fs.readFileSync(absPath, "utf8");
    const original = content;
    content = sanitizeForAI(content);

    const redacted = (original.match(/\[REDACTED\]/g) || []).length !== (content.match(/\[REDACTED\]/g) || []).length;
    if (redacted) {
        console.log(chalk.dim("  (Some values were redacted before sending)\n"));
    }

    // Pull context from latest audit report if available
    const dir = path.dirname(absPath);
    const report = getLatestReport(dir) || getLatestReport(process.cwd());
    let auditContext = "";
    if (report) {
        const { project, framework } = extractProjectInfo(report.content);
        auditContext = `This file belongs to a ${framework} project called "${project}".`;
    }

    const spinner = ora({ text: "  Reviewing file...", color: "yellow" }).start();

    const prompt = `You are a senior code reviewer. ${auditContext}

Review this file (${filename}) and provide:

## 🚨 Critical Issues
Bugs, security holes, breaking patterns — if any (with line numbers).

## ⚠️ Code Quality
Readability, naming, unnecessary complexity, dead code.

## ⚡ Performance
Inefficiencies, unnecessary re-renders/queries/loops.

## 📐 Best Practices
Framework-specific anti-patterns, missing patterns that should be used.

## ✅ What's Done Well
Acknowledge good patterns found in this file.

## 🔧 Suggested Improvements
Provide a rewritten version of the most problematic section(s). Show before/after.

---

\`\`\`${ext.slice(1)}
${content}
\`\`\`

Be specific with line numbers. Focus on actionable, high-impact feedback only.`;

    let result;
    try {
        result = await callAI([{ role: "user", content: prompt }], opts);
        spinner.stop();
    } catch (err) {
        spinner.stop();
        if (err.noKey) {
            console.log(chalk.yellow("\n  ⚠ AI not configured."));
            console.log(chalk.dim("  Run: ") + BRAND("npx tryappstack-audit ai-setup"));
        } else {
            console.log(chalk.red(`\n  ✗ AI error: ${err.message}`));
        }
        process.exit(1);
    }

    console.log("\n" + result.split("\n").map((l) => "  " + l).join("\n"));

    // Save to file
    const timestamp = new Date().toISOString().slice(0, 16).replace("T", "_").replace(":", "-");
    const outputDir = path.join(process.cwd(), "audits");
    fs.mkdirSync(outputDir, { recursive: true });
    const outputFile = path.join(outputDir, `review-${filename}-${timestamp}.md`);

    const fileContent = `# 🔎 AI File Review — ${filename}

> **File:** ${absPath}
> **Generated:** ${new Date().toISOString().slice(0, 19)}
> **AI Agent:** ${provider}

---

${result}

---

*Generated by [tryappstack-audit](https://tryappstack.vercel.app) · File review*
`;

    fs.writeFileSync(outputFile, fileContent);
    console.log("\n  " + chalk.green("✓") + " Saved: " + chalk.dim(outputFile) + "\n");
}

function confirmPrompt(question) {
    return new Promise((resolve) => {
        const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
        rl.question(question, (answer) => {
            rl.close();
            resolve(answer.trim().toLowerCase() === "y");
        });
    });
}

module.exports = aiReviewCommand;
